"use strict";
// automatically generated code, please do not change
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.ContainerEntity = exports.ParameterizableClass = exports.UnknownSourceLanguage = exports.FileAnchor = exports.Package = exports.AnnotationInstanceAttribute = exports.ScopingEntity = exports.IndexedFileAnchor = exports.SourcedEntity = exports.AnnotationInstance = exports.Parameter = exports.Class = exports.AnnotationTypeAttribute = exports.Inheritance = exports.Header = exports.PrimitiveType = exports.Access = exports.Association = exports.SmalltalkMonticelloSourceLanguage = exports.Enum = exports.TypeAlias = exports.GlobalVariable = exports.CustomSourceLanguage = exports.CaughtException = exports.ThrownException = exports.NamedEntity = exports.Method = exports.CompilationUnit = exports.ParameterizedType = exports.SourceLanguage = exports.Comment = exports.Invocation = exports.StructuralEntity = exports.DeclaredException = exports.JavaSourceLanguage = exports.Include = exports.Reference = exports.SmalltalkSourceLanguage = exports.SourceAnchor = exports.AnnotationType = exports.AbstractFileAnchor = exports.PharoAnchor = exports.ParameterType = exports.Type = exports.EnumValue = exports.MultipleFileAnchor = exports.Module = exports.LeafEntity = exports.Function = exports.Namespace = void 0;
exports.Attribute = exports.Entity = exports.BehaviouralEntity = exports.UnknownVariable = exports.SourceTextAnchor = exports.LocalVariable = exports.Exception = exports.ImplicitVariable = exports.DereferencedInvocation = exports.CSourceLanguage = void 0;
var namespace_1 = require("./namespace");
__createBinding(exports, namespace_1, "Namespace");
var function_1 = require("./function");
__createBinding(exports, function_1, "Function");
var leaf_entity_1 = require("./leaf_entity");
__createBinding(exports, leaf_entity_1, "LeafEntity");
var module_1 = require("./module");
__createBinding(exports, module_1, "Module");
var multiple_file_anchor_1 = require("./multiple_file_anchor");
__createBinding(exports, multiple_file_anchor_1, "MultipleFileAnchor");
var enum_value_1 = require("./enum_value");
__createBinding(exports, enum_value_1, "EnumValue");
var type_1 = require("./type");
__createBinding(exports, type_1, "Type");
var parameter_type_1 = require("./parameter_type");
__createBinding(exports, parameter_type_1, "ParameterType");
var pharo_anchor_1 = require("./pharo_anchor");
__createBinding(exports, pharo_anchor_1, "PharoAnchor");
var abstract_file_anchor_1 = require("./abstract_file_anchor");
__createBinding(exports, abstract_file_anchor_1, "AbstractFileAnchor");
var annotation_type_1 = require("./annotation_type");
__createBinding(exports, annotation_type_1, "AnnotationType");
var source_anchor_1 = require("./source_anchor");
__createBinding(exports, source_anchor_1, "SourceAnchor");
var smalltalk_source_language_1 = require("./smalltalk_source_language");
__createBinding(exports, smalltalk_source_language_1, "SmalltalkSourceLanguage");
var reference_1 = require("./reference");
__createBinding(exports, reference_1, "Reference");
var include_1 = require("./include");
__createBinding(exports, include_1, "Include");
var java_source_language_1 = require("./java_source_language");
__createBinding(exports, java_source_language_1, "JavaSourceLanguage");
var declared_exception_1 = require("./declared_exception");
__createBinding(exports, declared_exception_1, "DeclaredException");
var structural_entity_1 = require("./structural_entity");
__createBinding(exports, structural_entity_1, "StructuralEntity");
var invocation_1 = require("./invocation");
__createBinding(exports, invocation_1, "Invocation");
var comment_1 = require("./comment");
__createBinding(exports, comment_1, "Comment");
var source_language_1 = require("./source_language");
__createBinding(exports, source_language_1, "SourceLanguage");
var parameterized_type_1 = require("./parameterized_type");
__createBinding(exports, parameterized_type_1, "ParameterizedType");
var compilation_unit_1 = require("./compilation_unit");
__createBinding(exports, compilation_unit_1, "CompilationUnit");
var method_1 = require("./method");
__createBinding(exports, method_1, "Method");
var named_entity_1 = require("./named_entity");
__createBinding(exports, named_entity_1, "NamedEntity");
var thrown_exception_1 = require("./thrown_exception");
__createBinding(exports, thrown_exception_1, "ThrownException");
var caught_exception_1 = require("./caught_exception");
__createBinding(exports, caught_exception_1, "CaughtException");
var custom_source_language_1 = require("./custom_source_language");
__createBinding(exports, custom_source_language_1, "CustomSourceLanguage");
var global_variable_1 = require("./global_variable");
__createBinding(exports, global_variable_1, "GlobalVariable");
var type_alias_1 = require("./type_alias");
__createBinding(exports, type_alias_1, "TypeAlias");
var enum_1 = require("./enum");
__createBinding(exports, enum_1, "Enum");
var smalltalk_monticello_source_language_1 = require("./smalltalk_monticello_source_language");
__createBinding(exports, smalltalk_monticello_source_language_1, "SmalltalkMonticelloSourceLanguage");
var association_1 = require("./association");
__createBinding(exports, association_1, "Association");
var access_1 = require("./access");
__createBinding(exports, access_1, "Access");
var primitive_type_1 = require("./primitive_type");
__createBinding(exports, primitive_type_1, "PrimitiveType");
var header_1 = require("./header");
__createBinding(exports, header_1, "Header");
var inheritance_1 = require("./inheritance");
__createBinding(exports, inheritance_1, "Inheritance");
var annotation_type_attribute_1 = require("./annotation_type_attribute");
__createBinding(exports, annotation_type_attribute_1, "AnnotationTypeAttribute");
var class_1 = require("./class");
__createBinding(exports, class_1, "Class");
var parameter_1 = require("./parameter");
__createBinding(exports, parameter_1, "Parameter");
var annotation_instance_1 = require("./annotation_instance");
__createBinding(exports, annotation_instance_1, "AnnotationInstance");
var sourced_entity_1 = require("./sourced_entity");
__createBinding(exports, sourced_entity_1, "SourcedEntity");
var indexed_file_anchor_1 = require("./indexed_file_anchor");
__createBinding(exports, indexed_file_anchor_1, "IndexedFileAnchor");
var scoping_entity_1 = require("./scoping_entity");
__createBinding(exports, scoping_entity_1, "ScopingEntity");
var annotation_instance_attribute_1 = require("./annotation_instance_attribute");
__createBinding(exports, annotation_instance_attribute_1, "AnnotationInstanceAttribute");
var package_1 = require("./package");
__createBinding(exports, package_1, "Package");
var file_anchor_1 = require("./file_anchor");
__createBinding(exports, file_anchor_1, "FileAnchor");
var unknown_source_language_1 = require("./unknown_source_language");
__createBinding(exports, unknown_source_language_1, "UnknownSourceLanguage");
var parameterizable_class_1 = require("./parameterizable_class");
__createBinding(exports, parameterizable_class_1, "ParameterizableClass");
var container_entity_1 = require("./container_entity");
__createBinding(exports, container_entity_1, "ContainerEntity");
var c_source_language_1 = require("./c_source_language");
__createBinding(exports, c_source_language_1, "CSourceLanguage");
var dereferenced_invocation_1 = require("./dereferenced_invocation");
__createBinding(exports, dereferenced_invocation_1, "DereferencedInvocation");
var implicit_variable_1 = require("./implicit_variable");
__createBinding(exports, implicit_variable_1, "ImplicitVariable");
var exception_1 = require("./exception");
__createBinding(exports, exception_1, "Exception");
var local_variable_1 = require("./local_variable");
__createBinding(exports, local_variable_1, "LocalVariable");
var source_text_anchor_1 = require("./source_text_anchor");
__createBinding(exports, source_text_anchor_1, "SourceTextAnchor");
var unknown_variable_1 = require("./unknown_variable");
__createBinding(exports, unknown_variable_1, "UnknownVariable");
var behavioural_entity_1 = require("./behavioural_entity");
__createBinding(exports, behavioural_entity_1, "BehaviouralEntity");
var entity_1 = require("./entity");
__createBinding(exports, entity_1, "Entity");
var attribute_1 = require("./attribute");
__createBinding(exports, attribute_1, "Attribute");
